package org.sunbird.cb.hubservices.exception;

public enum ErrorCode {

	NODES_WITH_SAME_ID_EXISTS, GRAPH_TRANSACTIONAL_ERROR, GRAPH_SESSION_EXPIRED_ERROR, GRAPH_SESSION_ERROR,
	RECORD_NOT_FOUND_ERROR, MISSING_PROPERTY_ERROR, NODES_WITH_REVERSE_EDGE_EXISTS

}
